### ISSUE TITLE
Breaking change in  7.7.2,  net._normalizeConnectArgs was removed.

### ISSUE THREAD

**Issue by carlisliu** [othiym23/async-listener#100]
may get error like this:
![image](https://cloud.githubusercontent.com/assets/2157653/23789470/e3f8ba88-05b5-11e7-9062-aba3d24ce7a6.png)

**Comment by othiym23** [comment]
Fixed via ac301ba5780c7fecead05c76f053a5e87b523a6a / `async-listener@0.6.4`. Thanks for the heads up!
