### ISSUE TITLE
Help adding async-listener to citgm

### ISSUE THREAD

**Issue by watson** [othiym23/async-listener#111]
Hi @othiym23

Async-listener is depended upon by a lot of people in the community either directly via modules like continuation-local-storage, or indirectly by APM vendors.

Since async-listener heavily monkey patches node core, chances of it breaking due to simple internal refactors of node core is high (e.g. #109).

I'd therefore like to have async-listener added to [citgm](https://github.com/nodejs/citgm) so these issues are caught as early as possible in the future.

To be considered part of citgm, the module have to adhere to the following requirements:

- Module source code must be on Github.
- Published versions must include a tag on Github
- The test process must be executable with only the commands `npm install && npm test` using the tarball downloaded from the Github tag mentioned above
- The tests pass on supported major release lines
- The maintainers of the module remain responsive when there are problems
- At least one module maintainer must be added to the lookup maintainers field

At the moment this is not possible because the releases on GitHub isn't up to date (`git push --tags`). Also I wouldn't want to add this burden on you alone, so if you want, I'd like to help out with the maintenance and also adding my name to the list of contacts in citgm for async-listener.

**Comment by othiym23** [comment]
>At the moment this is not possible because the releases on GitHub isn't up to date (`git push --tags`).

Whoops! I had my work laptop configured to [push tags by default](https://stackoverflow.com/questions/2988088/do-git-tags-get-pushed-as-well), but when I lost that job, I forgot to copy the requisite configuration over to my personal machine. Tags pushed and configuration fixed.

>Also I wouldn't want to add this burden on you alone, so if you want, I'd like to help out with the maintenance and also adding my name to the list of contacts in citgm for async-listener.

```bash
$ npm owner add watson async-listener
+ watson (async-listener)
```

Also, you've been invited to join this repo as a maintainer. Let me know if you need anything else!

**Comment by watson** [comment]
Thanks 😃 Looking forward to be able to help out

**Comment by othiym23** [comment]
@Qard ^^ I just realized I should have checked in with you before Just Doing It, but it seems like a good idea to have someone actively working on APM with access to async-listener, no?

**Comment by Qard** [comment]
No worries, I definitely agree there!
