### ISSUE TITLE
Async-listener breaks method dispatch for promise subclasses

### ISSUE THREAD

**Issue by matthewloring** [othiym23/async-listener#112]
Test case:

```javascript
require('async-listener');
class P extends Promise {
  then() {
    console.log('In Subclass');
    return super.then.apply(this, arguments);
  }
}

P.resolve(5).then(v => {
  console.log(v);
});
```

Expected output (and observed when `require('async-listener');` is removed):
```
> In Subclass
> 5
```

Observed output:
```
> 5
```

This issue breaks the [got](https://npm.im/got) module (by breaking [p-cancelable](https://npm.im/p-cancelable)) and can be reproduced with node version 6.x and 8.x.

**Comment by matthewloring** [comment]
I believe this snippet illustrates the underlying problem:

```js
function WrappedPromise(executor) {
  var p = new Promise(executor);
  p.__proto__ = WrappedPromise.prototype;
  return p;
}

WrappedPromise.__proto__ = Promise;
WrappedPromise.prototype.__proto__ = Promise.prototype;

WrappedPromise.prototype.then = function then(onFulfilled, onRejected) {
  console.log('WrappedPromiseThen');
  return Promise.prototype.then.call(this, onFulfilled, onRejected);
};

class P extends WrappedPromise {
  then(onF, onR) {
    console.log('PThen');
    return Promise.prototype.then.call(this, onF, onR);
  }
}

(new P(res => { res(42); })).then(v => { console.log(v); });
```

Async-listener replaces the global promise with its own function-based class. Other modules extend the global Promise using ES6 class syntax. However, extending the function-based wrapper class does not result in the correct dispatch behavior. I think the best approach may be to rewrite the [`wrappedPromise`](https://github.com/othiym23/async-listener/blob/97d0fc92507058568fe78a34dcd88760a77aae07/index.js#L394) as an ES6 class. Does anyone have thoughts on that change or any other possible approaches?

**Comment by matthewloring** [comment]
@watson @Qard @othiym23 Any thoughts on this?

**Comment by watson** [comment]
@matthewloring Thanks for the ping 😃 I've commented on the PR

**Comment by matthewloring** [comment]
Can we re-opening after revert of the original fix due to https://github.com/othiym23/async-listener/issues/121. I don't have permission.

**Comment by hayes** [comment]
@watson opened a new issue #123

**Comment by watson** [comment]
I could also just reopen this if you guys think that is better?

**Comment by hayes** [comment]
I think the new issue is good
