### ISSUE TITLE
Travis CI allowed failures

### ISSUE THREAD

**Issue by watson** [othiym23/async-listener#116]
We current allow CI failures on Node.js 3 and 5: https://github.com/othiym23/async-listener/blob/97d0fc92507058568fe78a34dcd88760a77aae07/.travis.yml#L16-L19

I'm not sure if this was added because there were some issues on those versions or because they are not considered supported/important.

How would you guys think about not allowing failures on those versions by removing these lines from `.travis.yml`?

**Comment by watson** [comment]
As I just discovered on #117, this functionality have actually never worked. For now it's fixed in #117, but we still need to decide if this is actually needed 😄

**Comment by hayes** [comment]
I merged your PR to fix the expected old behavior, but I think this is still a valid question, I personally would lean towards not allowing failures, but I think this would be qood for @othiym23 to way in on

**Comment by othiym23** [comment]
I'd prefer to drop support for non-LTS and unsupported versions of Node than allow the tests to fail in CI. There are new issues popping up (example: #112) that are making me think hard about how far back backwards support should extend, but I don't see the value in supporting 3 and 5. Does anyone have any usage figures that suggest that anyone's using them?

**Comment by watson** [comment]
This is data from December 2016: https://nodesource.com/node-by-numbers
Here's data from April 2017 (go to 3:05): https://opbeat.com/community/posts/the-nodejs-process-making-decisions-that-impact-a-massive-ecosystem-by-james-snell/

As long as the tests don't fail (and this doesn't seem to have been a problem actually since this `allow_failures` didn't work), then I think we should keep testing against these versions a little while longer.

From a personal perspective (in Opbeat), we still have a lot of customers on 4.x and a few even on 0.10. So I'd like to keep old tests around unless it becomes a hassle to support
