### ISSUE TITLE
Typo in license? 

### ISSUE THREAD

**Issue by kakaying** [othiym23/async-listener#130]
Hi 
I noticed that in package.json file the author name is Forrest L Norvell <ogd@aoaioxxysz.net>, but in license, the copyright is for Forrest L Norvel. Just want to make sure if there is a typo. 

Thanks!

**Comment by watson** [comment]
Hi @kakaying 
Thanks for reaching out. That's my error. I added the license file recently because we never had one and I must have misspelled Norvell. I'll make sure to fix it
