### ISSUE TITLE
NPM warns about a vulnerability in semver

### ISSUE THREAD

**Issue by OIRNOIR** [othiym23/async-listener#145]
When installing async-listener then running `npm audit`, it shows as having 2 moderate security vulnerabilities caused by dependencies with vulnerable versions of `semver`. It would be great if these could be updated to fix the problem.
https://github.com/advisories/GHSA-c2qf-rxjj-qqgw

The `npm audit` output on a clean install (`npm i async-listener`) is below:

```
# npm audit report

semver  <7.5.2
Severity: moderate
semver vulnerable to Regular Expression Denial of Service - https://github.com/advisories/GHSA-c2qf-rxjj-qqgw
fix available via `npm audit fix --force`
Will install async-listener@0.6.3, which is a breaking change
node_modules/semver
  async-listener  >=0.6.4
  Depends on vulnerable versions of semver
  node_modules/async-listener

2 moderate severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force
```
`npm audit fix` has no effect, and `npm audit fix --force` would revert back to an extremely old version.

**Comment by Qard** [comment]
There are better tools for this at this point--async_hooks in Node.js core and AsyncLocalStorage if you just need it for request storage. Is there some reason you're still using async-listener?

**Comment by OIRNOIR** [comment]
It's being depended by another project, https://github.com/Unitech/pm2/, which I use

**Comment by Qard** [comment]
Maybe open an issue on their repo asking them to upgrade? This module has been largely unmaintained for many years now.

**Comment by budhitha** [comment]
> When installing async-listener then running `npm audit`, it shows as having 2 moderate security vulnerabilities caused by dependencies with vulnerable versions of `semver`. It would be great if these could be updated to fix the problem. [GHSA-c2qf-rxjj-qqgw](https://github.com/advisories/GHSA-c2qf-rxjj-qqgw)
> 
> The `npm audit` output on a clean install (`npm i async-listener`) is below:
> 
> ```
> # npm audit report
> 
> semver  <7.5.2
> Severity: moderate
> semver vulnerable to Regular Expression Denial of Service - https://github.com/advisories/GHSA-c2qf-rxjj-qqgw
> fix available via `npm audit fix --force`
> Will install async-listener@0.6.3, which is a breaking change
> node_modules/semver
>   async-listener  >=0.6.4
>   Depends on vulnerable versions of semver
>   node_modules/async-listener
> 
> 2 moderate severity vulnerabilities
> 
> To address all issues (including breaking changes), run:
>   npm audit fix --force
> ```
> 
> `npm audit fix` has no effect, and `npm audit fix --force` would revert back to an extremely old version.

The problem is still there.
![image](https://github.com/othiym23/async-listener/assets/61533037/f0d60aac-a7f0-41a3-8bad-a98062036efc)

**Comment by Qard** [comment]
Yes, as mentioned previously this module is not maintained at this point. There have been better alternatives for many years now.
