### ISSUE TITLE
Tests fail on node 0.11.5+

### ISSUE THREAD

**Issue by Qard** [othiym23/async-listener#26]
@othiym23 Here are the test logs from my run through of all the node 0.11.x versions.

https://gist.github.com/Qard/19a8f53534445de81b20

I'll work on fixing stuff tomorrow and submit some PRs.

**Comment by rkusa** [comment]
Btw, the async listener API has been moved to the `tracing` module in 0.11.12, but then completely removed in 0.11.15. The only remaining thing is: `process.binding('async_wrap')`

**Comment by Qard** [comment]
Yep, I'm aware of that. This module should work regardless of that though, as it's intended as a polyfill.

**Comment by othiym23** [comment]
It should probably warn and return instead of throwing for the 5 people using 0.11.11; that's a relic of when it was trying to match the native API 1:1. As for the rest, I'll take a look at the linked issues.

**Comment by Qard** [comment]
You can ignore the other errors I fixed everything in my PR except the 0.11.9/0.11.10 issue, which is a harder thing. I wonder if it would be exceedingly nefarious to just overwrite the built-in functions on those particular node versions...

**Comment by othiym23** [comment]
The answer is yes, but if it gets the job done without breaking anything, it's only a relatively minor violation of the monkeypatcher's code. :japanese_castle: I don't think it's a big deal, because 0.11.{9,10} are broken in a wide variety of ways.

**Comment by othiym23** [comment]
I'm going to call this one closed as it's too broad to figure out whether there's anything actionable remaining in here or not. Go ahead and open issues for specific failing test / version combos and we can take it from there.
