### ISSUE TITLE
npm WARN engine async-listener 

### ISSUE THREAD

**Issue by TofPlay** [othiym23/async-listener#30]
Hi
When I run this command:
```
$ slc loopback myapp
```
I have this message:
```
npm WARN engine async-listener@0.4.7: wanted: {"node":"<=0.11.8"} (current: {"node":"0.12.0","npm":"2.5.0"})
```

**Comment by othiym23** [comment]
Thanks for the reminder! `async-listener@0.5.1` was just published with a new `engines` field compatible with reality, so as soon as StrongLoop updates whatever dependency they're using that depends on `async-listener`, this warning should go away.
