### ISSUE TITLE
why not using domains?

### ISSUE THREAD

**Issue by yoavaa** [othiym23/async-listener#43]
Why is async listener not using domains? Using domains, all the context passing just works. The wrappers are just needed to tap into the different events, but even if one wrapper is missing, other wrappers down the line will continue to function.

What I mean is to replace the state that is stored in glue.js with a domain that is created for code that enters an async listener scope.

**Comment by madbence** [comment]
Domains are deprecated afaik.

**Comment by Qard** [comment]
Yes, they are deprecated. They are also made of pain and malice. I don't really want to get into a big, long rant about them. I'll just say they are _not_ a good API.

**Comment by yoavaa** [comment]
I am confused. Looking up the holy google search about nodejs and domains you only get documents about how cool those are and why you should use them [see here](https://www.google.co.il/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=nodejs%20domain). Only when looking for node.js domain deprecation we find discussions in the node forums that domains are deprecated. Even in the node APIs domains are not marked as deprecated, [rather as an unstable API](https://nodejs.org/api/domain.html).

If not using domains, that only leaves async-listener as an option to track an async flow and attach stuff to it - like long stack traces, "request scope data", profiling metrics, request IO metrics, etc. And async-listener itself does scary things with native promises. 

Are there other options? Other ways to tap into the event loop?

**Comment by Qard** [comment]
Keep in mind that node 0.12 is really, really old and soon to be replaced by io.js. Have a look at the [io.js domain docs](https://iojs.org/api/domain.html) to see the deprecation warning.

I'd agree that having to resort to userland monkey-patching is rather sad, and is a big part of why I helped start the [tracing working group](http://github.com/nodejs/tracing-wg). But, unfortunately, there is no other adequate option currently. The `async-listener` module is intended as a polyfill for the AsyncListener API that used to be in node, backing domains, but it ended up getting ripped out and is currently being replaced gradually by `async_wrap`, though it is not ready yet. The module needs to have a relatively wide version support, so brand new APIs can only be used with an appropriate fallback, which is what the ugly bits of this module are for.

Also of note is that promises are managed by the microtask queue in V8, which domains can't interact with and therefore can cause some very unexpected behaviour.

If and when some better, more stable API for tracking stack movement comes into existence, we'll certainly be looking into updating this module to use that instead. Until then, it's probably best to continue using the gross monkey-patching and avoid domains.

I know it sucks. I'm all too familiar with what lurks beneath these seemingly innocuous APIs.
