### ISSUE TITLE
Context not preserved after Promise.catch

### ISSUE THREAD

**Issue by wonnage** [othiym23/async-listener#45]
```
const cls = require('continuation-local-storage')
const context = cls.createNamespace('context')
context.run(() => { 
  context.set('foo', 3); 
  Promise.resolve('test')
    .then(() => console.log(cls.getNamespace('context').get('foo'))) 
})

=> 3

const cls = require('continuation-local-storage')
const context = cls.createNamespace('context')
context.run(() => { 
  context.set('foo', 3); 
  Promise.resolve('test')
    .catch(() => {})
    .then(() => console.log(cls.getNamespace('context').get('foo'))) 
})

=> undefined
````

**Comment by wonnage** [comment]
Looks like the context is not preserved if you chain a catch and it's not hit (i.e, the promise was not actually rejected)

**Comment by Qard** [comment]
Good catch! :smirk: 

Seems catch is not patched at all. @hayes You have any ideas on this one? If not, I'll see about looking into this on Monday.

**Comment by hayes** [comment]
My guess is that it must be a change in how v8 implements promises. It used to be that catch was implemented on top of then, so you only needed to wrap then

**Comment by hayes** [comment]
Hmm, looks like its always been broken. I think I know whats wrong, trying to figure out the best way to fix it

**Comment by hayes** [comment]
#47 should fix this. Going to think on it over night, because it feels a little hacky
