### ISSUE TITLE
Requiring async listener results in incorrect function lengths.

### ISSUE THREAD

**Issue by matthewloring** [othiym23/async-listener#53]
Run with async-listener @0.5.7 and node v5.7.1.

```
> var fs = require('fs');
undefined
> fs.readFile.length
3
> require('async-listener')
{}
> fs.readFile.length
0
```

**Comment by Qard** [comment]
It's because it is wrapped generically. Everything becomes 0 argument length. https://github.com/othiym23/async-listener/blob/master/index.js#L13-L21

The other option would be to wrap *everything* manually, but that'd be kind of unpleasant...

**Comment by matthewloring** [comment]
Would you be open to argument length specialization like this: https://github.com/nodejs/node/blob/master/lib/events.js#L74? I know it isn't pretty but it may have a positive performance impact in addition to preserving function length properly.

**Comment by Qard** [comment]
Yeah, it'd probably work fine to have `activator(fn)` check fn length and then return different versions of the patch function. I'd be okay with that approach. I'm happy with any performance improvements, so long as it doesn't make the code substantially harder to maintain. :smile_cat:

**Comment by hayes** [comment]
I am fine with returning function with a fixed number of arguments, but not with actually using those arguments to proxy if arguments.length is incorrect.

I am not sure if I interpreted your intentions correctly, but I would want a check that looks somehting like:
```javascript
return function(a, b, c) {
  if (arguments.length <= 3) return original.call(a, b, c)
  else return original.apply(this, arguments)
}
```

**Comment by Qard** [comment]
I believe the intent is to match the number of parameters encoded in the signature, not how many arguments are actually received at call time. Not sure what the exact use case is. I could see if maybe being helpful for feature detection.

@matthewloring Would you mind explaining why this matters to you? Do you have a particular need for function lengths to be accurate?

**Comment by Jeff-Lewis** [comment]
For what it's worth, this bit me once as a lib (I think it was an older version of Mongoose) was checking a passed callback function for # of parameters and its return behavior depended on it. Whether that's a good idea or not, without interfaces in js, I see libs doing things like this. In general, it would be nice to provide a wrapped function that is closest in state to the original function as possible.

**Comment by hayes** [comment]
this would probably work as a generic way to wrap things:

```javascript
function wrapWithNameAndLength (fn, wrapper) {
  var args = []
  for (var i = 0; i < fn.length; ++i) args.push('arg_' + i)
  return new Function('original, len', '' + 
    'return function ' + fn.name + '(' + args.join(', ') + ') {\n' +
    '  if (arguments.length === 0) return original.call(this)\n' +
    '  if (arguments.length <= ' + fn.length + ') return original.call(this, ' + args.join(', ') + ')\n' +
    '  else return original.apply(this, arguments)\n' +
    '}' +
  '')(wrapper(fn))
}
```

**Comment by Jeff-Lewis** [comment]
Be careful with [new Function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function). It does not create a closure.

> Note: Functions created with the Function constructor do not create closures to their creation contexts; they always are created in the global scope. When running them, they will only be able to access their own local variables and global ones, not the ones from the scope in which the Function constructor was called. This is different from using eval with code for a function expression.

**Comment by Qard** [comment]
I'd rather not deopt the entire surface area of the core API...I'd rather try to preserve length with a reasonable number of hard-coded functions and fallback to the existing dynamic function if there's too many parameters.

**Comment by hayes** [comment]
probably should have mentioned that I didn't mean that as a recommendation for every place that functions are wrapped. I'm not sure how bad the deop would be for this type of wrapping though.  But if there were cases (and I'm not convinced there are) where function arity is important, it would be better to use a generic approach than to have a bunch of custom functions (maybe)

@Jeff-Lewis that snippet doesn't depend on a closure, it uses arguments to pass what it needs from the out closure.

**Comment by faithseed** [comment]
https://github.com/laverdet/node-fibers/commit/969e81d57090f2184b56525205a15fb7e6554187#diff-df4dea30d9f8df82d0cf772e8351c579

old fiber library does check function length and throw errors after require async-listener.

**Comment by matthewloring** [comment]
I agree that we should avoid forcing deopts. I believe @Qard is referring to something like the snippet below. Maybe we could hard code up to 5 arguments? It isn't pretty but the bodies of the functions are identical and they're colocated so it shouldn't increase the maintenance burden.
```javascript
// Shim activator for functions that have callback last
function activator(fn) {
  // Preserve function length for small arg count functions.
  switch (fn.length) {
    case 1:
      return function (a) {
        var index = arguments.length - 1;
        if (typeof arguments[index] === "function") {
          arguments[index] = wrapCallback(arguments[index]);
        }
        return fn.apply(this, arguments);
      };
    case 2:
      return function (a, b) {
        var index = arguments.length - 1;
        if (typeof arguments[index] === "function") {
          arguments[index] = wrapCallback(arguments[index]);
        }
        return fn.apply(this, arguments);
      };
    // ...
    default:
      return function () {
        var index = arguments.length - 1;
        if (typeof arguments[index] === "function") {
          arguments[index] = wrapCallback(arguments[index]);
        }
        return fn.apply(this, arguments);
      };
  }
}
```

**Comment by Qard** [comment]
Yep, that's what I had in mind. Though certain uses of the arguments object also deopts, so might want to do something about that too.

**Comment by matthewloring** [comment]
I was able to convince V8 to not disable optimization for these wrappers with the implementation below. If everyone is on board with a solution along these lines, I'll open a PR and we can continue discussion there.

```javascript
function activator(fn) {
  var fallback = function () {
    var index = arguments.length - 1;
    if (typeof arguments[index] === "function") {
      arguments[index] = wrapCallback(arguments[index]);
    }
    return fn.apply(this, arguments);
  };
  // Preserve function length for small arg count functions.
  switch (fn.length) {
    case 1:
      return function (cb) {
        if (arguments.length !== 1) return fallback.apply(this, arguments);
        if (typeof cb === "function") cb = wrapCallback(cb);
        return fn.call(this, cb);
      };
    case 2:
      return function (a, cb) {
        if (arguments.length !== 2) return fallback.apply(this, arguments);
        if (typeof cb === "function") cb = wrapCallback(cb);
        return fn.call(this, a, cb);
      };
    // ...
    default:
      return fallback;
  }
}
```

**Comment by Qard** [comment]
I'm onboard. How about you, @hayes?

**Comment by hayes** [comment]
works for me

**Comment by Qard** [comment]
Also, <= might be faster than !== for fallback since less arguments would still work in the call.

**Comment by matthewloring** [comment]
If we use `<=` we will have to find the last non-undefined argument to determine which is the callback to be wrapped. Do you think the added logic is worth it?

**Comment by Qard** [comment]
Ah, right. Ignore me! :smile_cat:
