### ISSUE TITLE
http requests failing in 0.6.1

### ISSUE THREAD

**Issue by peterjroberts** [othiym23/async-listener#64]
The changes between 0.6.0 and 0.6.1 is causing issues with http requests timing out in our apps. We get async-listener as a dependency of continuation-local-storage, http calls are made via wreck.

Seen on multiple 0.10.x node versions.

At this point our best theory is the http request doesn't have the port argument/has the wrong one. Based on some telnet request snooping
0.6.0
socket(PF_INET, SOCK_STREAM, IPPROTO_IP) = 3
connect(3, {sa_family=AF_INET, sin_port=htons(443), sin_addr=inet_addr("x.x.x.x")}, 16) = 0

0.6.1
socket(PF_INET, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, IPPROTO_IP) = 10
connect(10, {sa_family=AF_INET, sin_port=htons(0), sin_addr=inet_addr("x.x.x.x")}, 16) = -1 EINPROGRESS (Operation now in progress)

**Comment by montgomery1944** [comment]
We have the same problem. Part of the system stopped working because of this change.

**Comment by alarre** [comment]
+1

Same problem using 0.10.X . Did a deploy and the system stopped working due to "^0.6.0" dependency en continous-local-storage

**Comment by FDREAL** [comment]
I had the exact same problem, also with 0.10.X. Is it possible to do a rollback until this is further analysed?

**Comment by Fdiazreal** [comment]
I had the exact same problem, also with 0.10.X. Is it possible to do a rollback until this is further analysed?

**Comment by peterjroberts** [comment]
@Fdiazreal you can add async-listener as a dependency of your own project with version '0.6.0' to get that effect.

**Comment by XinV** [comment]
+1. set to '0.6.0' seems working

**Comment by Qard** [comment]
Very strange. Must be a result of #63, somehow. I'll revert that.

**Comment by Qard** [comment]
I've reverted #63 and released 0.6.2. I'll do some more investigation into #63 to figure out why that would've been causing timeouts.

**Comment by peterjroberts** [comment]
@Qard thanks, I can confirm this does resolve the issue we were seeing with 0.6.1.

**Comment by Fdiazreal** [comment]
@Qard Same here. Thanks for the quick response.
